# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import random
class NakliLlm :

  def __init__(self):
    print("LLM Created")

  def predict(self,prompt):
    response_list = [
        "delhi is capital of india",
        "ipl is cricket league",
        "ai stands for artificial intelligence"
    ]
    return {"response" : random.choice(response_list)}

llm = NakliLlm()

llm.predict("who is capital of india")

class NakliPromptTemplate :

  def __init__(self , template , input_varibles ):
    self.template = template
    self.input_varibles = input_varibles

  def format(self , input_dict):
    return self.template.format(**input_dict)

template = NakliPromptTemplate(
    template = "Write a {length} poem about {topic}",
    input_varibles=['length' , 'topic']
)

prompt = template.format({'length' : "short" , 'topic':'india'})

llm.predict(prompt)

class NakliLlmChain :
  def __init__(self,prompt,llm):
    self.llm=llm
    self.prompt=prompt
  def run(self,input_dict):
    final_prompt = self.prompt.format(input_dict)
    result = self.llm.predict(final_prompt)
    return result['response']

chain =  NakliLlmChain(prompt,llm)

chain.run({'length':'short','topic':'india'})

